name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: "pip" # caching pip dependencies
      - name: Ruff + Black Lint
        run: |
          ./scripts/lint.sh -c

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
          cache: "pip" # caching pip dependencies
      - name: Python ${{ matrix.python-version }} Unit Tests
        run: |
          ./scripts/test.sh
